class EarnedTitle {
  const EarnedTitle({
    required this.id,
    required this.name,
    required this.lore,
    required this.earnedAt,
  });

  final String id;
  final String name;
  final String lore;
  final DateTime earnedAt;

  Map<String, dynamic> toJson() => {
        'id': id,
        'name': name,
        'lore': lore,
        'earned_at': earnedAt.toIso8601String(),
      };

  factory EarnedTitle.fromJson(Map<String, dynamic> json) => EarnedTitle(
        id: json['id'] as String,
        name: json['name'] as String,
        lore: json['lore'] as String,
        earnedAt: DateTime.parse(json['earned_at'] as String),
      );
}

/// Well-known title identifiers — must match App Store Connect achievement IDs.
abstract final class TitleIds {
  static const dawnPhantom = 'title_dawn_phantom';
  static const ironStreak = 'title_iron_streak';
  static const ghostHunter = 'title_ghost_hunter';
  static const apexCalibrated = 'title_apex_calibrated';
  static const theUnbroken = 'title_the_unbroken';
  static const firstTen = 'title_first_ten_km';
}

/// Canonical title definitions. Lore is generated by AI at unlock time;
/// these are fallback descriptions.
const _titleDefs = {
  TitleIds.dawnPhantom: ('The Dawn Phantom', '10 runs completed before 6am'),
  TitleIds.ironStreak: ('Iron Streak', '30-day consecutive run streak'),
  TitleIds.ghostHunter: ('Ghost Hunter', 'Beat 5 of your own boss quests'),
  TitleIds.apexCalibrated: (
    'Apex Calibrated',
    'Gait model reached high confidence'
  ),
  TitleIds.theUnbroken: (
    'The Unbroken',
    'Completed a run with readiness under 40'
  ),
  TitleIds.firstTen: ('First 10K', 'Ran your first 10 km distance'),
};

EarnedTitle buildTitle(String id, {String? aiLore}) {
  final def = _titleDefs[id];
  return EarnedTitle(
    id: id,
    name: def?.$1 ?? id,
    lore: aiLore ?? def?.$2 ?? '',
    earnedAt: DateTime.now(),
  );
}
