// ignore_for_file: avoid_print
// Regenerates the auto-generated sections of CODEMAP.md.
library;

/// Usage: dart run tool/generate_codemap.dart
import 'dart:convert';
import 'dart:io';

const _beginMarker = '<!-- CODEMAP_AUTO_BEGIN -->';
const _endMarker = '<!-- CODEMAP_AUTO_END -->';
const _hotFileLineThreshold = 250;

void main() {
  final libDir = Directory('lib');
  if (!libDir.existsSync()) {
    stderr.writeln('Run from repository root (lib/ not found).');
    exit(1);
  }

  final files = libDir
      .listSync(recursive: true)
      .whereType<File>()
      .where((f) => f.path.endsWith('.dart'))
      .where((f) => !f.path.endsWith('.g.dart'))
      .where((f) => !f.path.endsWith('.freezed.dart'))
      .toList()
    ..sort((a, b) => a.path.compareTo(b.path));

  final hotFiles = <({String path, int lines})>[];
  final layerLines = <String>[];

  for (final file in files) {
    final rel = file.path.replaceAll('\\', '/');
    final content = file.readAsStringSync();
    final lineCount = const LineSplitter().convert(content).length;
    if (lineCount > _hotFileLineThreshold) {
      hotFiles.add((path: rel, lines: lineCount));
    }

    final classes = RegExp(r'^class (\w+)', multiLine: true)
        .allMatches(content)
        .map((m) => m.group(1))
        .whereType<String>()
        .toList();
    final summary = classes.isEmpty
        ? _firstCommentLine(content) ?? 'Dart module'
        : classes.take(3).join(', ') + (classes.length > 3 ? ', …' : '');
    layerLines.add('| `$rel` | $lineCount | $summary |');
  }

  hotFiles.sort((a, b) => b.lines.compareTo(a.lines));

  final buffer = StringBuffer()
    ..writeln(_beginMarker)
    ..writeln()
    ..writeln('## Layer Map (auto-generated)')
    ..writeln()
    ..writeln('| File | Lines | Summary |')
    ..writeln('|------|------:|---------|')
    ..writeln(layerLines.join('\n'))
    ..writeln()
    ..writeln('## Hot Files (do not grow)')
    ..writeln()
    ..writeln('| File | Lines | Target |')
    ..writeln('|------|------:|--------|')
    ..writeln(
      hotFiles
          .take(20)
          .map(
            (f) =>
                '| `${f.path}` | ${f.lines} | Split if > $_hotFileLineThreshold lines |',
          )
          .join('\n'),
    )
    ..writeln()
    ..writeln(
      '_Generated by `dart run tool/generate_codemap.dart` — '
      '${files.length} hand-written Dart files._',
    )
    ..writeln()
    ..writeln(_endMarker);

  final codemapPath = 'CODEMAP.md';
  final codemapFile = File(codemapPath);
  if (!codemapFile.existsSync()) {
    stderr.writeln(
      '$codemapPath not found. Create the manual sections first.',
    );
    exit(1);
  }

  final existing = codemapFile.readAsStringSync();
  final start = existing.indexOf(_beginMarker);
  final end = existing.indexOf(_endMarker);

  if (start == -1 || end == -1) {
    stderr.writeln('Markers not found in $codemapPath.');
    exit(1);
  }

  final before = existing.substring(0, start);
  final autoSection = buffer.toString().trimRight();

  // Normalize EOF — do not preserve trailing blank lines after the end marker.
  final updated = '$before$autoSection\n';
  codemapFile.writeAsStringSync(updated);
  print('Updated $codemapPath (${files.length} files indexed).');
}

String? _firstCommentLine(String content) {
  for (final line in content.split('\n')) {
    final trimmed = line.trim();
    if (trimmed.startsWith('///')) {
      return trimmed.replaceFirst('///', '').trim();
    }
    if (!trimmed.startsWith('//') &&
        !trimmed.startsWith('import ') &&
        trimmed.isNotEmpty &&
        !trimmed.startsWith('part ')) {
      break;
    }
  }
  return null;
}
